{ config, pkgs, ... }:
let
  # Import each section, passing config as parameter
  bar = import ./noctalia-sections/bar.nix config;
  general = import ./noctalia-sections/general.nix config;
  notifications = import ./noctalia-sections/notifications.nix config;
  wallpaper = import ./noctalia-sections/wallpaper.nix config;
  launcher = import ./noctalia-sections/launcher.nix config;
  session = import ./noctalia-sections/session.nix config;
  system = import ./noctalia-sections/system.nix config;
  extras = import ./noctalia-sections/extras.nix config;

  templateDir = ./templates;

  # Post-hook: replace starship palette section with template output,
  # then reload running instances via SIGHUP.
  starshipPostHook = pkgs.writeShellScript "starship-palette-update" ''
    STARSHIP="''${XDG_CONFIG_HOME:-$HOME/.config}/starship.toml"
    PALETTE="''${XDG_CACHE_HOME:-$HOME/.cache}/noctalia/starship-palette.toml"
    [ -f "$STARSHIP" ] && [ -f "$PALETTE" ] || exit 0
    # Strip the header line from the generated palette fragment
    COLORS=$(${pkgs.gnused}/bin/sed '1d' "$PALETTE")
    ${pkgs.gnused}/bin/sed -i '/^\[palettes\.onix-dark\]/,/^\[/{/^\[palettes\.onix-dark\]/!{/^\[/!d}}' "$STARSHIP"
    ${pkgs.gnused}/bin/sed -i "/^\[palettes\.onix-dark\]/a\\$COLORS" "$STARSHIP"
  '';
in
{
  programs.noctalia-shell = {
    enable = true;

    # Material 3 color mapping from theme palette
    colors = {
      mPrimary = config.theme.data.accent.hex;
      mOnPrimary = config.theme.data.bg.hex;
      mSecondary = config.theme.data.accent2.hex;
      mOnSecondary = config.theme.data.bg.hex;
      mTertiary = config.theme.data.purple.hex;
      mOnTertiary = config.theme.data.bg.hex;
      mError = config.theme.data.red.hex;
      mOnError = config.theme.data.bg.hex;
      mSurface = config.theme.data.bg.hex;
      mSurfaceVariant = config.theme.data.bg_highlight.hex;
      mOnSurface = config.theme.data.fg.hex;
      mOnSurfaceVariant = config.theme.data.fg_dim.hex;
      mOutline = config.theme.data.border.hex;
      mShadow = config.theme.data.bg_dark.hex;
      mHover = config.theme.data.bg_highlight.hex;
      mOnHover = config.theme.data.fg.hex;
    };

    # User templates for apps without built-in Noctalia support.
    # Built-in templates handle: niri, kitty, btop, helix.
    # User templates handle: fish, bat, delta, eza, starship, swayosd.
    # wezterm colors are generated by Nix in wezterm.nix via xdg.configFile.
    user-templates = {
      templates = {
        fish = {
          input_path = "${templateDir}/fish-colors.fish";
          output_path = "~/.config/fish/conf.d/noctalia-colors.fish";
        };
        bat = {
          input_path = "${templateDir}/bat.tmTheme";
          output_path = "~/.config/bat/themes/noctalia.tmTheme";
          post_hook = "bat cache --build 2>/dev/null || true";
        };
        delta = {
          input_path = "${templateDir}/delta.gitconfig";
          output_path = "~/.config/git/noctalia-delta-colors";
        };
        eza = {
          input_path = "${templateDir}/eza-theme.yml";
          output_path = "~/.config/eza/theme.yml";
        };
        starship = {
          input_path = "${templateDir}/starship-palette.toml";
          output_path = "~/.cache/noctalia/starship-palette.toml";
          post_hook = "${starshipPostHook}";
        };
        swayosd = {
          input_path = "${templateDir}/swayosd.css";
          output_path = "~/.config/swayosd/style.css";
          post_hook = "systemctl --user restart swayosd.service 2>/dev/null || true";
        };
      };
    };

    # Merge all section settings
    settings = bar // general // notifications // wallpaper // launcher // session // system // extras;
  };

  # Install Onix color scheme where Noctalia discovers downloaded schemes
  xdg.configFile."noctalia/colorschemes/Onix/Onix.json".source = ./colorschemes/Onix.json;
}
