_: {
  terraform.required_version = ">= 1.0";

  # Production environment backend - S3 with Garage
  # Backend is configured via backend.tf generated by terranix-devshell

  # Production environment protection
  terraform.required_providers = {
    # Add your production providers here
    # cloudflare = {
    #   source = "cloudflare/cloudflare";
    #   version = "~> 4.0";
    # };
  };

  # Production environment resources
  resource.null_resource.prod_health_check = {
    provisioner."local-exec" = {
      command = "echo '🚀 Production Environment - Live infrastructure'";
    };

    # Add lifecycle rules for production resources
    lifecycle = {
      prevent_destroy = true; # Prevent accidental destruction
    };
  };

  # Example: Production DNS records (if using Cloudflare)
  # resource.cloudflare_record.prod_main = {
  #   zone_id = "your-zone-id";
  #   name = "@";
  #   content = "production-server-ip";
  #   type = "A";
  #   ttl = 3600;
  #   proxied = true;
  #   comment = "Production main site";
  # };

  # Production environment outputs
  output.environment = {
    value = "production";
    sensitive = false;
  };

  output.state_location = {
    value = "Encrypted in Clan vars: terraform-state-infrastructure-prod";
    sensitive = false;
  };

  output.deployment_target = {
    value = "aspen1";
    sensitive = false;
  };

  output.warning = {
    value = "⚠️ PRODUCTION ENVIRONMENT - Changes affect live systems";
  };
}
