# Noctalia theme sync — propagates runtime color changes to all themed apps.
#
# Noctalia writes colors.json when wallpaper or dark/light mode changes.
# This module generates a sync script that reads those colors and writes
# override config files for each app. The script is called from Noctalia's
# hooks (wallpaperChange, darkModeChange).
#
# Build-time configs are the seed/defaults. This script overrides them at runtime.
{ config, pkgs, ... }:
let
  theme = config.theme.data;

  # The sync script reads Noctalia's colors.json and generates per-app overrides.
  # Uses jq to parse the JSON and bash heredocs for templates.
  syncScript = pkgs.writeShellScript "noctalia-theme-sync" ''
    set -euo pipefail

    COLORS_FILE="''${XDG_CONFIG_HOME:-$HOME/.config}/noctalia/colors.json"

    if [ ! -f "$COLORS_FILE" ]; then
      echo "noctalia-theme-sync: no colors.json found, skipping"
      exit 0
    fi

    # Read Material 3 tokens from Noctalia's colors.json
    read_color() {
      ${pkgs.jq}/bin/jq -r ".$1 // empty" "$COLORS_FILE"
    }

    # Map Material 3 tokens to theme color slots
    PRIMARY=$(read_color mPrimary)
    ON_PRIMARY=$(read_color mOnPrimary)
    SECONDARY=$(read_color mSecondary)
    SURFACE=$(read_color mSurface)
    SURFACE_VARIANT=$(read_color mSurfaceVariant)
    ON_SURFACE=$(read_color mOnSurface)
    ON_SURFACE_VARIANT=$(read_color mOnSurfaceVariant)
    OUTLINE=$(read_color mOutline)
    ERROR=$(read_color mError)
    SHADOW=$(read_color mShadow)

    # If primary is empty, colors.json isn't populated yet
    if [ -z "$PRIMARY" ]; then
      echo "noctalia-theme-sync: colors.json has no mPrimary, skipping"
      exit 0
    fi

    # Fallbacks
    : "''${ON_PRIMARY:=#000000}"
    : "''${SECONDARY:=$PRIMARY}"
    : "''${SURFACE:=#1a1a1a}"
    : "''${SURFACE_VARIANT:=#262626}"
    : "''${ON_SURFACE:=#e6e6e6}"
    : "''${ON_SURFACE_VARIANT:=#b3b3b3}"
    : "''${OUTLINE:=#404040}"
    : "''${ERROR:=#ff4444}"
    : "''${SHADOW:=#0d0d0d}"

    # Strip # for apps that need bare hex
    strip() { echo "''${1#\#}"; }
    PRIMARY_BARE=$(strip "$PRIMARY")
    ON_PRIMARY_BARE=$(strip "$ON_PRIMARY")
    SECONDARY_BARE=$(strip "$SECONDARY")
    SURFACE_BARE=$(strip "$SURFACE")
    SURFACE_VARIANT_BARE=$(strip "$SURFACE_VARIANT")
    ON_SURFACE_BARE=$(strip "$ON_SURFACE")
    ON_SURFACE_VARIANT_BARE=$(strip "$ON_SURFACE_VARIANT")
    OUTLINE_BARE=$(strip "$OUTLINE")
    ERROR_BARE=$(strip "$ERROR")
    SHADOW_BARE=$(strip "$SHADOW")

    # Hex to decimal for ANSI codes
    hex2dec() {
      printf '%d' "0x$1"
    }
    hex2ansi() {
      local bare=$(strip "$1")
      local r=$(hex2dec "''${bare:0:2}")
      local g=$(hex2dec "''${bare:2:2}")
      local b=$(hex2dec "''${bare:4:2}")
      echo "38;2;$r;$g;$b"
    }

    mkdir -p "''${XDG_CONFIG_HOME:-$HOME/.config}"/{fish/conf.d,helix/themes,btop/themes,swayosd}

    # ── Fish shell colors ──────────────────────────────────────────
    cat > "''${XDG_CONFIG_HOME:-$HOME/.config}/fish/conf.d/noctalia-colors.fish" <<FISH
    # Generated by noctalia-theme-sync — do not edit
    set -g fish_color_normal $ON_SURFACE_BARE
    set -g fish_color_autosuggestion $OUTLINE_BARE
    set -g fish_color_command $PRIMARY_BARE
    set -g fish_color_error $ERROR_BARE --bold
    set -g fish_color_param $SECONDARY_BARE
    set -g fish_color_quote $ON_SURFACE_VARIANT_BARE
    set -g fish_color_redirection $SECONDARY_BARE
    set -g fish_color_end $SECONDARY_BARE
    set -g fish_color_comment $OUTLINE_BARE --italics
    set -g fish_color_operator $SECONDARY_BARE
    set -g fish_color_escape $SECONDARY_BARE
    set -g fish_color_cwd $PRIMARY_BARE
    set -g fish_color_search_match --background=$SURFACE_VARIANT_BARE
    set -g fish_color_selection --background=$SURFACE_VARIANT_BARE
    set -g fish_pager_color_completion $ON_SURFACE_BARE
    set -g fish_pager_color_description $OUTLINE_BARE --italics
    set -g fish_pager_color_prefix $PRIMARY_BARE --bold --underline
    set -g fish_pager_color_progress $ON_SURFACE_BARE --background=$SURFACE_VARIANT_BARE
    set -g fish_pager_color_selected_background --background=$SURFACE_VARIANT_BARE
    FISH

    # ── Starship palette ──────────────────────────────────────────
    STARSHIP_FILE="''${XDG_CONFIG_HOME:-$HOME/.config}/starship.toml"
    if [ -f "$STARSHIP_FILE" ]; then
      # Replace the palette section in-place using sed
      ${pkgs.gnused}/bin/sed -i '/^\[palettes\.onix-dark\]/,/^$/{
        s/^color_orange = .*/color_orange = "'"$ON_SURFACE"'"/
        s/^color_cyan = .*/color_cyan = "'"$ON_SURFACE_VARIANT"'"/
        s/^color_gray = .*/color_gray = "'"$OUTLINE"'"/
        s/^color_green = .*/color_green = "'"$SURFACE_VARIANT"'"/
        s/^color_bg1 = .*/color_bg1 = "'"$SURFACE"'"/
        s/^color_bg3 = .*/color_bg3 = "'"$SURFACE_VARIANT"'"/
        s/^color_fg0 = .*/color_fg0 = "'"$ON_SURFACE"'"/
      }' "$STARSHIP_FILE"
    fi

    # ── Helix theme ───────────────────────────────────────────────
    cat > "''${XDG_CONFIG_HOME:-$HOME/.config}/helix/themes/noctalia-dark.toml" <<HELIX
    # Generated by noctalia-theme-sync
    [theme]
    "ui.background" = { bg = "$SURFACE" }
    "ui.text" = { fg = "$ON_SURFACE" }
    "ui.statusline" = { bg = "$PRIMARY", fg = "$ON_PRIMARY", modifiers = ["bold"] }
    "ui.cursor" = { bg = "$PRIMARY" }
    "ui.selection" = { bg = "$SURFACE_VARIANT" }
    "ui.menu" = { bg = "$SURFACE_VARIANT", fg = "$ON_SURFACE" }
    "ui.menu.selected" = { bg = "$PRIMARY", fg = "$ON_PRIMARY" }
    "ui.popup" = { bg = "$SURFACE_VARIANT", fg = "$ON_SURFACE" }
    "ui.linenr" = { fg = "$OUTLINE" }
    "ui.linenr.selected" = { fg = "$PRIMARY", modifiers = ["bold"] }
    "keyword" = { fg = "$PRIMARY", modifiers = ["bold"] }
    "function" = { fg = "$SECONDARY" }
    "string" = { fg = "$ON_SURFACE_VARIANT" }
    "comment" = { fg = "$OUTLINE", modifiers = ["italic"] }
    "constant.numeric" = { fg = "$SECONDARY" }
    "operator" = { fg = "$PRIMARY", modifiers = ["bold"] }
    "error" = { fg = "$ERROR", modifiers = ["bold"] }
    HELIX

    # ── btop theme ────────────────────────────────────────────────
    cat > "''${XDG_CONFIG_HOME:-$HOME/.config}/btop/themes/custom-theme.theme" <<BTOP
    # Generated by noctalia-theme-sync
    theme[main_bg]="$SURFACE"
    theme[main_fg]="$ON_SURFACE"
    theme[title]="$ON_SURFACE"
    theme[hi_fg]="$PRIMARY"
    theme[selected_bg]="$SURFACE_VARIANT"
    theme[selected_fg]="$ON_SURFACE"
    theme[inactive_fg]="$ON_SURFACE_VARIANT"
    theme[proc_misc]="$SECONDARY"
    theme[cpu_box]="$OUTLINE"
    theme[mem_box]="$OUTLINE"
    theme[net_box]="$OUTLINE"
    theme[proc_box]="$OUTLINE"
    theme[div_line]="$OUTLINE"
    theme[temp_start]="$PRIMARY"
    theme[temp_mid]="$SECONDARY"
    theme[temp_end]="$ERROR"
    theme[cpu_start]="$PRIMARY"
    theme[cpu_mid]="$SECONDARY"
    theme[cpu_end]="$ERROR"
    theme[free_start]="$PRIMARY"
    theme[free_mid]="$SECONDARY"
    theme[free_end]="$ERROR"
    theme[cached_start]="$PRIMARY"
    theme[cached_mid]="$SECONDARY"
    theme[cached_end]="$ERROR"
    theme[available_start]="$PRIMARY"
    theme[available_mid]="$SECONDARY"
    theme[available_end]="$ERROR"
    theme[used_start]="$PRIMARY"
    theme[used_mid]="$SECONDARY"
    theme[used_end]="$ERROR"
    theme[download_start]="$PRIMARY"
    theme[download_mid]="$SECONDARY"
    theme[download_end]="$ERROR"
    theme[upload_start]="$PRIMARY"
    theme[upload_mid]="$SECONDARY"
    theme[upload_end]="$ERROR"
    BTOP

    # ── eza theme ─────────────────────────────────────────────────
    cat > "''${XDG_CONFIG_HOME:-$HOME/.config}/eza/theme.yml" <<EZA
    # Generated by noctalia-theme-sync
    filekinds:
      normal: {foreground: "$ON_SURFACE"}
      directory: {foreground: "$PRIMARY"}
      executable: {foreground: "$SECONDARY"}
      symlink: {foreground: "$SECONDARY"}
      pipe: {foreground: "$ON_SURFACE_VARIANT"}
      socket: {foreground: "$ON_SURFACE_VARIANT"}
    perms:
      user_read: {foreground: "$ERROR"}
      user_write: {foreground: "$PRIMARY"}
      user_execute_file: {foreground: "$SECONDARY"}
    git:
      modified: {foreground: "$SECONDARY"}
      new: {foreground: "$PRIMARY"}
      deleted: {foreground: "$ERROR"}
      conflicted: {foreground: "$ERROR"}
      typechange: {foreground: "$SECONDARY"}
    EZA

    # ── Delta (git diff) ─────────────────────────────────────────
    DELTA_INCLUDE="''${XDG_CONFIG_HOME:-$HOME/.config}/git/noctalia-delta-colors"
    mkdir -p "$(dirname "$DELTA_INCLUDE")"
    cat > "$DELTA_INCLUDE" <<DELTA
    # Generated by noctalia-theme-sync
    [delta]
        plus-style = syntax "$PRIMARY"
        minus-style = syntax "$ERROR"
        plus-emph-style = syntax "$PRIMARY"
        minus-emph-style = syntax "$ERROR"
        line-numbers-plus-style = $PRIMARY
        line-numbers-minus-style = $ERROR
        line-numbers-left-style = $OUTLINE
        line-numbers-right-style = $OUTLINE
        line-numbers-zero-style = $OUTLINE
        file-style = $SECONDARY bold
        file-decoration-style = $SECONDARY ul
        hunk-header-style = $PRIMARY bold
        hunk-header-decoration-style = $PRIMARY box
    DELTA

    # ── SwayOSD ───────────────────────────────────────────────────
    cat > "''${XDG_CONFIG_HOME:-$HOME/.config}/swayosd/style.css" <<SWAYOSD
    /* Generated by noctalia-theme-sync */
    window {
      border-radius: ${toString theme.hypr.rounding}px;
      opacity: 0.97;
      border: 2px solid $PRIMARY;
      background-color: ''${SURFACE}e6;
    }
    label {
      font-family: 'CaskaydiaMono Nerd Font', monospace;
      font-size: 11pt;
      color: $ON_SURFACE;
    }
    image { color: $PRIMARY; }
    progressbar { border-radius: ${toString theme.hypr.rounding}px; }
    progress { background-color: $PRIMARY; }
    SWAYOSD

    # Restart swayosd to pick up new CSS
    ${pkgs.systemd}/bin/systemctl --user restart swayosd.service 2>/dev/null || true

    # ── Bat theme ─────────────────────────────────────────────────
    BAT_THEME_DIR="''${XDG_CONFIG_HOME:-$HOME/.config}/bat/themes"
    mkdir -p "$BAT_THEME_DIR"
    cat > "$BAT_THEME_DIR/noctalia.tmTheme" <<BAT
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>name</key><string>Noctalia</string>
      <key>settings</key>
      <array>
        <dict><key>settings</key><dict>
          <key>background</key><string>$SURFACE</string>
          <key>foreground</key><string>$ON_SURFACE</string>
          <key>caret</key><string>$PRIMARY</string>
          <key>lineHighlight</key><string>$SURFACE_VARIANT</string>
          <key>selection</key><string>$OUTLINE</string>
        </dict></dict>
        <dict><key>name</key><string>Comment</string><key>scope</key><string>comment</string>
          <key>settings</key><dict><key>foreground</key><string>$OUTLINE</string><key>fontStyle</key><string>italic</string></dict></dict>
        <dict><key>name</key><string>String</string><key>scope</key><string>string</string>
          <key>settings</key><dict><key>foreground</key><string>$ON_SURFACE_VARIANT</string></dict></dict>
        <dict><key>name</key><string>Keyword</string><key>scope</key><string>keyword</string>
          <key>settings</key><dict><key>foreground</key><string>$PRIMARY</string><key>fontStyle</key><string>bold</string></dict></dict>
        <dict><key>name</key><string>Function</string><key>scope</key><string>entity.name.function</string>
          <key>settings</key><dict><key>foreground</key><string>$SECONDARY</string></dict></dict>
        <dict><key>name</key><string>Type</string><key>scope</key><string>entity.name.type</string>
          <key>settings</key><dict><key>foreground</key><string>$ON_SURFACE_VARIANT</string></dict></dict>
      </array>
    </dict>
    </plist>
    BAT
    # Rebuild bat cache so it picks up the new theme
    ${pkgs.bat}/bin/bat cache --build 2>/dev/null || true

    echo "noctalia-theme-sync: all apps updated"
  '';
in
{
  # Install the sync script
  home.packages = [ (pkgs.writeShellScriptBin "noctalia-theme-sync" (builtins.readFile syncScript)) ];
}
