# Generated by noctalia — do not edit
set -g fish_color_normal {{colors.on_surface.default.hex_stripped}}
set -g fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -g fish_color_command {{colors.primary.default.hex_stripped}}
set -g fish_color_error {{colors.error.default.hex_stripped}} --bold
set -g fish_color_param {{colors.secondary.default.hex_stripped}}
set -g fish_color_quote {{colors.on_surface_variant.default.hex_stripped}}
set -g fish_color_redirection {{colors.tertiary.default.hex_stripped}}
set -g fish_color_end {{colors.secondary.default.hex_stripped}}
set -g fish_color_comment {{colors.outline.default.hex_stripped}} --italics
set -g fish_color_operator {{colors.tertiary.default.hex_stripped}}
set -g fish_color_escape {{colors.tertiary.default.hex_stripped}}
set -g fish_color_cwd {{colors.primary.default.hex_stripped}}
set -g fish_color_cwd_root {{colors.error.default.hex_stripped}}
set -g fish_color_user {{colors.secondary.default.hex_stripped}}
set -g fish_color_host {{colors.primary.default.hex_stripped}}
set -g fish_color_host_remote {{colors.tertiary.default.hex_stripped}}
set -g fish_color_cancel -r
set -g fish_color_search_match --background={{colors.surface_container_high.default.hex_stripped}}
set -g fish_color_selection --background={{colors.surface_container_high.default.hex_stripped}}
set -g fish_color_status {{colors.error.default.hex_stripped}}
set -g fish_color_valid_path --underline
set -g fish_color_history_current --bold

# Pager colors
set -g fish_pager_color_completion {{colors.on_surface.default.hex_stripped}}
set -g fish_pager_color_description {{colors.outline.default.hex_stripped}} --italics
set -g fish_pager_color_prefix {{colors.primary.default.hex_stripped}} --bold --underline
set -g fish_pager_color_progress {{colors.on_surface.default.hex_stripped}} --background={{colors.surface_container_high.default.hex_stripped}}
set -g fish_pager_color_selected_background --background={{colors.surface_container_high.default.hex_stripped}}
