-- Generated by noctalia — do not edit
return {
  background = '{{colors.terminal_background.default.hex}}',
  foreground = '{{colors.terminal_foreground.default.hex}}',
  cursor_bg = '{{colors.terminal_cursor.default.hex}}',
  cursor_fg = '{{colors.terminal_cursor_text.default.hex}}',
  cursor_border = '{{colors.terminal_cursor.default.hex}}',
  selection_bg = '{{colors.terminal_selection_bg.default.hex}}',
  selection_fg = '{{colors.terminal_selection_fg.default.hex}}',

  ansi = {
    '{{colors.terminal_normal_black.default.hex}}',
    '{{colors.terminal_normal_red.default.hex}}',
    '{{colors.terminal_normal_green.default.hex}}',
    '{{colors.terminal_normal_yellow.default.hex}}',
    '{{colors.terminal_normal_blue.default.hex}}',
    '{{colors.terminal_normal_magenta.default.hex}}',
    '{{colors.terminal_normal_cyan.default.hex}}',
    '{{colors.terminal_normal_white.default.hex}}',
  },
  brights = {
    '{{colors.terminal_bright_black.default.hex}}',
    '{{colors.terminal_bright_red.default.hex}}',
    '{{colors.terminal_bright_green.default.hex}}',
    '{{colors.terminal_bright_yellow.default.hex}}',
    '{{colors.terminal_bright_blue.default.hex}}',
    '{{colors.terminal_bright_magenta.default.hex}}',
    '{{colors.terminal_bright_cyan.default.hex}}',
    '{{colors.terminal_bright_white.default.hex}}',
  },

  tab_bar = {
    background = '{{colors.shadow.default.hex}}',
    active_tab = {
      bg_color = '{{colors.primary.default.hex}}',
      fg_color = '{{colors.on_primary.default.hex}}',
    },
    inactive_tab = {
      bg_color = '{{colors.surface_container_high.default.hex}}',
      fg_color = '{{colors.on_surface_variant.default.hex}}',
    },
    inactive_tab_hover = {
      bg_color = '{{colors.surface_container_high.default.hex}}',
      fg_color = '{{colors.on_surface.default.hex}}',
    },
    new_tab = {
      bg_color = '{{colors.shadow.default.hex}}',
      fg_color = '{{colors.on_surface_variant.default.hex}}',
    },
    new_tab_hover = {
      bg_color = '{{colors.surface_container_high.default.hex}}',
      fg_color = '{{colors.on_surface.default.hex}}',
    },
  },
}
