{
  lib,
  config,
  pkgs,
  self,
  ...
}:
let
  plugins = self.packages.${pkgs.stdenv.hostPlatform.system}.wasm-plugins;
  wasm = import "${self}/lib/wasm.nix" { inherit plugins; };

  allMachines = (wasm.evalNickelFile ../core/machines.ncl).machines;
  builderKeyPath = config.clan.core.vars.generators.nix-builder-ssh.files."id_ed25519".path;
  iroh-ssh = pkgs.callPackage "${self}/pkgs/iroh-ssh" { };
  hostname = config.networking.hostName;

  # Read SSH host public key from vars (generated by clan vars)
  getHostKey =
    machine:
    let
      path = self + "/vars/per-machine/${machine}/openssh/ssh.id_ed25519.pub/value";
    in
    if builtins.pathExists path then lib.trim (builtins.readFile path) else null;

  # Read iroh-ssh node-id from vars (generated by clan vars)
  getNodeId =
    machine:
    let
      path = self + "/vars/per-machine/${machine}/iroh-ssh/node-id/value";
    in
    if builtins.pathExists path then lib.trim (builtins.readFile path) else null;

  # Machines with the remote-builders tag that are also builders
  # (i.e., they exist in the inventory and have this tag).
  # Each builder is reached via addresses.lan if set, otherwise via iroh-${name}.
  builderMachines = lib.filterAttrs (
    name: m: builtins.elem "remote-builders" (m.tags or [ ]) && name != hostname # exclude self
  ) allMachines;

  # Build the nix.buildMachines list from inventory data
  allBuildMachines = lib.mapAttrsToList (
    name: m:
    let
      lan = m.addresses.lan or null;
      # Prefer LAN if available, otherwise use iroh alias
      sshHostName = if lan != null then lan else "iroh-${name}";
      systems =
        if m.system == "aarch64-darwin" then
          [
            "aarch64-darwin"
            "aarch64-linux"
          ]
        else
          [ m.system ];
    in
    {
      protocol = "ssh-ng";
      hostName = sshHostName;
      inherit systems;
      maxJobs = 16;
      speedFactor = if m.system == "aarch64-darwin" then 12 else 20;
      sshUser = if (m.machineClass or "nixos") == "darwin" then "brittonr" else "root";
      sshKey = builderKeyPath;
      supportedFeatures =
        if m.system == "aarch64-darwin" then
          [ "big-parallel" ]
        else
          [
            "nixos-test"
            "big-parallel"
            "kvm"
          ];
    }
  ) builderMachines;

  # Machines reachable via iroh (have a node-id in vars, no LAN address)
  irohMachines = lib.filterAttrs (
    name: m:
    let
      nodeId = getNodeId name;
      lan = m.addresses.lan or null;
    in
    nodeId != null && lan == null
  ) allMachines;

  # Generate SSH known hosts from inventory + vars
  knownHostEntries = lib.mapAttrs' (
    name: m:
    let
      lan = m.addresses.lan or null;
      hasIroh = getNodeId name != null;
      hostKey = getHostKey name;
      # The SSH hostname used to reach this machine
      sshAlias = if lan == null && hasIroh then "iroh-${name}" else null;
      hostNames =
        lib.optional (lan != null) lan
        ++ lib.optional (sshAlias != null) sshAlias
        ++ lib.optional (name != (if lan != null then lan else "")) name;
    in
    lib.nameValuePair (if sshAlias != null then sshAlias else name) {
      inherit hostNames;
      publicKey = hostKey;
    }
  ) (lib.filterAttrs (_: _: true) (lib.filterAttrs (name: _: getHostKey name != null) allMachines));
in
{
  # Dedicated SSH keypair for the nix daemon (root) to authenticate
  # to remote builders. Root can't access user SSH agents, so it
  # needs its own key on disk.
  clan.core.vars.generators.nix-builder-ssh = {
    files."id_ed25519" = { };
    files."id_ed25519.pub".secret = false;
    runtimeInputs = [ pkgs.openssh ];
    script = ''
      ssh-keygen -t ed25519 -N "" -C "nix-builder@${hostname}" -f "$out/id_ed25519"
    '';
  };

  # Enable distributed builds to offload compilation to faster machines
  nix = {
    distributedBuilds = lib.mkDefault true;

    settings = {
      # Allow build machines to fetch from caches directly
      builders-use-substitutes = lib.mkDefault true;
    };

    buildMachines = allBuildMachines;
  };

  programs.ssh = {
    knownHosts = knownHostEntries;

    # System-wide ProxyCommand for iroh-ssh reachable machines.
    # Root's nix-daemon needs this to reach builders behind NAT.
    extraConfig = lib.concatStrings (
      lib.mapAttrsToList (
        name: _m:
        let
          nodeId = getNodeId name;
        in
        lib.optionalString (nodeId != null) ''
          Host iroh-${name}
            HostName ${name}
            HostkeyAlias iroh-${name}
            ProxyCommand ${iroh-ssh}/bin/iroh-ssh proxy ${nodeId}
            ServerAliveInterval 15
            ServerAliveCountMax 3
            ConnectionAttempts 5
        ''
      ) irohMachines
    );
  };
}
