{
  lib,
  config,
  pkgs,
  self,
  wasm,
  nclMachines,
  ...
}:
let
  allMachines = nclMachines;
  builderData = wasm.evalNickelFile ./builder-targets.ncl;
  builderKeyPath = config.clan.core.vars.generators.nix-builder-ssh.files."id_ed25519".path;
  hostname = config.networking.hostName;

  getSshHost =
    sshHost:
    let
      parts = builtins.match "([^@]+@)?(.+)" sshHost;
    in
    if parts == null then sshHost else builtins.elemAt parts 1;

  # Read SSH host public key from vars (generated by clan vars)
  getHostKey =
    machine:
    let
      path = self + "/vars/per-machine/${machine}/openssh/ssh.id_ed25519.pub/value";
    in
    if builtins.pathExists path then lib.trim (builtins.readFile path) else null;

  # Builder targets from Nickel (validated against machine registry).
  builderTargetNames = builtins.map (t: t.name) builderData.targets;
  builderTargetsByName = builtins.listToAttrs (
    builtins.map (t: {
      inherit (t) name;
      value = t;
    }) builderData.targets
  );

  builderMachines = lib.filterAttrs (
    name: _: builtins.elem name builderTargetNames && name != hostname
  ) allMachines;

  # Build the nix.buildMachines list from Nickel target metadata + machine addresses.
  # Use LAN address if available, otherwise use hostname directly (reachable via Tailscale MagicDNS).
  allBuildMachines = lib.mapAttrsToList (
    name: m:
    let
      target = builderTargetsByName.${name};
      lan = m.addresses.lan or null;
      sshHostName = if lan != null then lan else name;
    in
    {
      protocol = "ssh-ng";
      hostName = sshHostName;
      inherit (target)
        systems
        maxJobs
        speedFactor
        sshUser
        supportedFeatures
        ;
      sshKey = builderKeyPath;
    }
  ) builderMachines;

  # Generate SSH known hosts from inventory + vars
  knownHostEntries = lib.mapAttrs' (
    name: m:
    let
      lan = m.addresses.lan or null;
      hostKey = getHostKey name;
      hostNames =
        lib.optional (lan != null) lan ++ lib.optional (name != (if lan != null then lan else "")) name;
    in
    lib.nameValuePair name {
      inherit hostNames;
      publicKey = hostKey;
    }
  ) (lib.filterAttrs (name: _: getHostKey name != null) allMachines);

  rootDeployHosts = lib.unique (
    lib.flatten (
      lib.mapAttrsToList (
        name: m:
        let
          lan = m.addresses.lan or null;
          targetHost = m.deploy.targetHost or null;
        in
        lib.optionals (name != hostname) (
          lib.optional (targetHost != null) (getSshHost targetHost)
          ++ lib.optional (lan != null) lan
          ++ [ name ]
        )
      ) allMachines
    )
  );
in
{
  clan.core.vars.generators.nix-builder-ssh = {
    files."id_ed25519" = { };
    files."id_ed25519.pub".secret = false;
    runtimeInputs = [ pkgs.openssh ];
    script = ''
      ssh-keygen -t ed25519 -N "" -C "nix-builder@${hostname}" -f "$out/id_ed25519"
    '';
  };

  nix = {
    distributedBuilds = lib.mkDefault true;
    settings.builders-use-substitutes = lib.mkDefault true;
    buildMachines = allBuildMachines;
  };

  programs.ssh = {
    extraConfig = lib.mkAfter ''
      Match localuser root host ${lib.concatStringsSep "," rootDeployHosts}
        IdentityAgent none
        IdentityFile ${builderKeyPath}
        IdentitiesOnly yes
        StrictHostKeyChecking accept-new
    '';
    knownHosts = knownHostEntries;
  };
}
