{
  lib,
  config,
  pkgs,
  self,
  wasm,
  nclMachines,
  ...
}:
let
  allMachines = nclMachines;
  builderData = wasm.evalNickelFile ./builder-targets.ncl;
  builderKeyPath = config.clan.core.vars.generators.nix-builder-ssh.files."id_ed25519".path;
  iroh-ssh = pkgs.callPackage "${self}/pkgs/iroh-ssh" { };
  hostname = config.networking.hostName;

  # Read SSH host public key from vars (generated by clan vars)
  getHostKey =
    machine:
    let
      path = self + "/vars/per-machine/${machine}/openssh/ssh.id_ed25519.pub/value";
    in
    if builtins.pathExists path then lib.trim (builtins.readFile path) else null;

  # Read iroh-ssh node-id from vars (generated by clan vars)
  getNodeId =
    machine:
    let
      path = self + "/vars/per-machine/${machine}/iroh-ssh/node-id/value";
    in
    if builtins.pathExists path then lib.trim (builtins.readFile path) else null;

  # Builder targets from Nickel (validated against machine registry).
  builderTargetNames = builtins.map (t: t.name) builderData.targets;
  builderTargetsByName = builtins.listToAttrs (
    builtins.map (t: {
      inherit (t) name;
      value = t;
    }) builderData.targets
  );

  builderMachines = lib.filterAttrs (
    name: _: builtins.elem name builderTargetNames && name != hostname
  ) allMachines;

  # Build the nix.buildMachines list from Nickel target metadata + machine addresses.
  allBuildMachines = lib.mapAttrsToList (
    name: m:
    let
      target = builderTargetsByName.${name};
      lan = m.addresses.lan or null;
      sshHostName = if lan != null then lan else "iroh-${name}";
    in
    {
      protocol = "ssh-ng";
      hostName = sshHostName;
      inherit (target)
        systems
        maxJobs
        speedFactor
        sshUser
        supportedFeatures
        ;
      sshKey = builderKeyPath;
    }
  ) builderMachines;

  # Machines reachable via iroh (have a node-id in vars, no LAN address)
  irohMachines = lib.filterAttrs (
    name: m:
    let
      nodeId = getNodeId name;
      lan = m.addresses.lan or null;
    in
    nodeId != null && lan == null
  ) allMachines;

  # Generate SSH known hosts from inventory + vars
  knownHostEntries = lib.mapAttrs' (
    name: m:
    let
      lan = m.addresses.lan or null;
      hasIroh = getNodeId name != null;
      hostKey = getHostKey name;
      sshAlias = if lan == null && hasIroh then "iroh-${name}" else null;
      hostNames =
        lib.optional (lan != null) lan
        ++ lib.optional (sshAlias != null) sshAlias
        ++ lib.optional (name != (if lan != null then lan else "")) name;
    in
    lib.nameValuePair (if sshAlias != null then sshAlias else name) {
      inherit hostNames;
      publicKey = hostKey;
    }
  ) (lib.filterAttrs (name: _: getHostKey name != null) allMachines);
in
{
  clan.core.vars.generators.nix-builder-ssh = {
    files."id_ed25519" = { };
    files."id_ed25519.pub".secret = false;
    runtimeInputs = [ pkgs.openssh ];
    script = ''
      ssh-keygen -t ed25519 -N "" -C "nix-builder@${hostname}" -f "$out/id_ed25519"
    '';
  };

  nix = {
    distributedBuilds = lib.mkDefault true;
    settings.builders-use-substitutes = lib.mkDefault true;
    buildMachines = allBuildMachines;
  };

  programs.ssh = {
    knownHosts = knownHostEntries;

    extraConfig = lib.concatStrings (
      lib.mapAttrsToList (
        name: _m:
        let
          nodeId = getNodeId name;
        in
        lib.optionalString (nodeId != null) ''
          Host iroh-${name}
            HostName ${name}
            HostkeyAlias iroh-${name}
            ProxyCommand ${iroh-ssh}/bin/iroh-ssh proxy ${nodeId}
            ServerAliveInterval 15
            ServerAliveCountMax 3
            ConnectionAttempts 5
        ''
      ) irohMachines
    );
  };
}
