# vLLM/Ray/RCCL cluster network selector for paired Strix Halo hosts.
# Prefers the RDMA tag when present, otherwise falls back to Thunderbolt TCP.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  envRelativePath = "vllm-cluster/network.env";
  envAbsolutePath = "/etc/${envRelativePath}";
  headHost = "aspen1";
  rayPort = 6379;
  rdmaNetworkName = "50-rdma-cluster";
  thunderboltNetworkName = "60-thunderbolt-bridge";
  rdmaInterface = "rdma0";
  thunderboltInterface = "br-tbt";
  rdmaBackend = "rdma";
  thunderboltBackend = "thunderbolt";
  rdmaTransport = "roce";
  thunderboltTransport = "tcp";
  rdmaNcclIbDisable = "0";
  thunderboltNcclIbDisable = "1";

  clusterNodes = {
    aspen1 = {
      role = "head";
      rdmaAddress = "192.168.100.1";
      thunderboltAddress = "10.10.10.1";
    };
    aspen2 = {
      role = "worker";
      rdmaAddress = "192.168.100.2";
      thunderboltAddress = "10.10.10.2";
    };
  };

  hostname = config.networking.hostName;
  node = clusterNodes.${hostname} or null;
  headNode = clusterNodes.${headHost};
  hasRdmaNetwork = lib.hasAttrByPath [
    "systemd"
    "network"
    "networks"
    rdmaNetworkName
  ] config;
  hasThunderboltNetwork = lib.hasAttrByPath [
    "systemd"
    "network"
    "networks"
    thunderboltNetworkName
  ] config;
  selectedBackend =
    if hasRdmaNetwork then
      rdmaBackend
    else if hasThunderboltNetwork then
      thunderboltBackend
    else
      null;
  selectedAddress =
    clusterNode:
    if selectedBackend == rdmaBackend then clusterNode.rdmaAddress else clusterNode.thunderboltAddress;
  workerNodes = lib.filterAttrs (name: _: name != headHost) clusterNodes;
  workerAddresses = lib.mapAttrsToList (_: selectedAddress) workerNodes;
  selectedNetwork =
    if node == null || selectedBackend == null then
      null
    else if selectedBackend == rdmaBackend then
      {
        backend = rdmaBackend;
        interface = rdmaInterface;
        localAddress = node.rdmaAddress;
        headAddress = headNode.rdmaAddress;
        transport = rdmaTransport;
        ncclIbDisable = rdmaNcclIbDisable;
      }
    else
      {
        backend = thunderboltBackend;
        interface = thunderboltInterface;
        localAddress = node.thunderboltAddress;
        headAddress = headNode.thunderboltAddress;
        transport = thunderboltTransport;
        ncclIbDisable = thunderboltNcclIbDisable;
      };
  clusterNetwork =
    if selectedNetwork == null then
      null
    else
      selectedNetwork
      // {
        host = hostname;
        inherit (node) role;
        inherit
          headHost
          rayPort
          workerAddresses
          ;
      };

  envText = ''
    # Generated by inventory/tags/vllm-cluster-network.nix.
    # Source this file before starting Ray/vLLM, or run commands via vllm-cluster-env.
    VLLM_CLUSTER_BACKEND=${selectedNetwork.backend}
    VLLM_CLUSTER_TRANSPORT=${selectedNetwork.transport}
    VLLM_CLUSTER_INTERFACE=${selectedNetwork.interface}
    VLLM_CLUSTER_HOST=${hostname}
    VLLM_CLUSTER_ROLE=${node.role}
    VLLM_CLUSTER_HEAD_HOST=${headHost}
    VLLM_CLUSTER_HEAD_IP=${selectedNetwork.headAddress}
    VLLM_CLUSTER_LOCAL_IP=${selectedNetwork.localAddress}
    VLLM_CLUSTER_RAY_PORT=${toString rayPort}
    RAY_ADDRESS=${selectedNetwork.headAddress}:${toString rayPort}
    RAY_NODE_IP_ADDRESS=${selectedNetwork.localAddress}
    VLLM_HOST_IP=${selectedNetwork.localAddress}
    NCCL_SOCKET_IFNAME=${selectedNetwork.interface}
    GLOO_SOCKET_IFNAME=${selectedNetwork.interface}
    TP_SOCKET_IFNAME=${selectedNetwork.interface}
    NCCL_IB_DISABLE=${selectedNetwork.ncclIbDisable}
  '';

  vllmClusterEnv = pkgs.writeShellApplication {
    name = "vllm-cluster-env";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      env_file="${envAbsolutePath}"

      if [ ! -r "$env_file" ]; then
        echo "missing vLLM cluster env file: $env_file" >&2
        exit 1
      fi

      if [ "$#" -eq 0 ]; then
        cat "$env_file"
        exit 0
      fi

      set -a
      # shellcheck disable=SC1090,SC1091
      . "$env_file"
      set +a

      exec "$@"
    '';
  };
in
{
  options.onix.vllmClusterNetwork = lib.mkOption {
    type = lib.types.attrsOf lib.types.anything;
    default = { };
    description = "Selected fast-link cluster network metadata for vLLM, Lemonade, and related inference services.";
  };

  config = lib.mkMerge [
    {
      assertions = [
        {
          assertion = node != null;
          message = ''
            The vllm-cluster-network tag requires ${hostname} to be declared in clusterNodes.
            Add the host's RDMA/Thunderbolt addresses before assigning the tag.
          '';
        }
        {
          assertion = selectedBackend != null;
          message = ''
            The vllm-cluster-network tag requires either rdma-cluster or thunderbolt-link networking on ${hostname}.
            Add one of those network tags before assigning vllm-cluster-network.
          '';
        }
      ];
    }

    (lib.mkIf (selectedNetwork != null) {
      onix.vllmClusterNetwork = clusterNetwork;

      environment = {
        etc.${envRelativePath}.text = envText;
        systemPackages = [ vllmClusterEnv ];
      };
    })
  ];
}
