{ ... }:
{
  instances = {

    # Test VM instance for development and testing
    "test-vm" = {
      module.name = "microvm";
      module.input = "self";
      roles.server = {
        tags."desktop" = { };
        settings = {
          vmName = "test-vm";
          autostart = true;
          hypervisor = "cloud-hypervisor";
          vcpu = 2;
          mem = 1024;

          # Network configuration
          interfaces = [
            {
              type = "tap";
              id = "vm-test";
              mac = "02:00:00:01:01:01";
            }
          ];

          # Enable vsock for systemd notification
          vsockCid = 3;

          # Credentials to pass from host (will be auto-generated by clan vars)
          credentials = {
            api-key = {
              destination = "API-KEY";
            };
            db-password = {
              destination = "DB-PASSWORD";
            };
            jwt-secret = {
              destination = "JWT-SECRET";
            };
          };

          # Static configuration via OEM strings
          staticOemStrings = [
            "io.systemd.credential:ENVIRONMENT=test"
            "io.systemd.credential:CLUSTER=britton-desktop"
          ];

          # Guest configuration
          rootPassword = "test"; # For testing only!
          firewallPorts = [
            80
            443
          ];

          # Enable demo credential logging service
          enableDemoCredentialService = true;

          # Guest packages
          guestPackages = [ ];
        };
      };
    };

    # NOTE: Additional VM configurations can be added here
    # Examples: vault-vm, dev-container, etc.
    # Currently only test-vm is enabled for testing

  };
}