_: {
  terraform.required_version = ">= 1.0";

  # Staging environment backend - S3 with Garage
  # Backend is configured via backend.tf generated by terranix-devshell

  # Staging environment resources
  resource.null_resource.staging_test = {
    provisioner."local-exec" = {
      command = "echo '🚧 Staging Environment - Pre-production testing'";
    };
  };

  # Example: Staging DNS records (if using Cloudflare)
  # resource.cloudflare_record.staging_subdomain = {
  #   zone_id = "your-zone-id";
  #   name = "staging";
  #   content = "192.168.1.146";  # britton-dev machine
  #   type = "A";
  #   ttl = 600;
  #   comment = "Staging environment";
  # };

  # Staging environment validations
  # Add validation resources to test before production

  # Staging environment outputs
  output.environment = {
    value = "staging";
  };

  output.state_location = {
    value = "Encrypted in Clan vars: terraform-state-infrastructure-staging";
  };

  output.deployment_target = {
    value = "britton-dev (192.168.1.146)";
  };
}
